from typing import TypedDict, List, Annotated
from operator import add
from langchain_core.messages import BaseMessage

class AgentState(TypedDict, total=False):
    """
    Defines the shared state for the Text-to-SQL agent graph.
    This state acts as the agent's memory, passed and updated between each node.
    """
    query: str                  # The user's natural language question
    sql_query: str              # The SQL query generated by the LLM
    db_results: str             # The raw data returned from the SQLite database
    error: str                  # Any SQL execution error (used to trigger self-correction)
    summary: str                # The final, business-friendly answer
    
    # Conversation history, using 'add' reducer to append messages rather than overwrite
    messages: Annotated[List[BaseMessage], add]