import os
import sqlite3
from dotenv import load_dotenv
from typing import TypedDict, List, Annotated
from operator import add
from langchain_core.messages import BaseMessage, SystemMessage, HumanMessage, AIMessage
from langchain_openai import ChatOpenAI
from langgraph.graph import StateGraph, START, END
from langgraph.checkpoint.memory import MemorySaver

# 1. Load environment variables from the .env file (API keys)
load_dotenv()

# 2. Define the Agent's Memory
class AgentState(TypedDict, total=False):
    """
    Defines the shared state for the Text-to-SQL agent graph.
    """
    query: str                  # The user's natural language question
    sql_query: str              # The SQL query generated by the LLM
    db_results: str             # The raw data returned from the SQLite database
    raw_data: list              # Structured data for the Streamlit UI dataframe
    error: str                  # Any SQL execution error
    summary: str                # The final, business-friendly answer
    messages: Annotated[List[BaseMessage], add] 

# 3. Define Node 1: SQL Generator
def generate_sql(state: AgentState) -> dict:
    """
    Node 1: Takes the user query and the database schema, 
    and uses an LLM to generate a valid SQLite query.
    If an error occurred in a previous step, it uses it to self-correct.
    """
    print("--- NODE: GENERATING SQL ---")
    question = state.get("query")
    error = state.get("error", "")
    
    # Read the database schema we extracted earlier
    try:
        with open("schema.txt", "r", encoding="utf-8") as f:
            schema = f.read()
    except FileNotFoundError:
        schema = "Schema file not found. Please run extract_schema.py first."
        
    # Initialize the LLM (using gpt-4o-mini for speed and cost efficiency)
    # Temperature is set to 0 because we want deterministic, precise SQL code, not creativity
    llm = ChatOpenAI(model="gpt-4o-mini", temperature=0)
    
    # Craft the system prompt
    system_prompt = f"""You are an expert SQLite data analyst.
    Your task is to translate the user's question into a valid SQLite query.
    
    Here is the schema of the database:
    {schema}
    
Rules:
    1. Return ONLY the raw SQL query.
    2. Do not wrap the SQL in markdown formatting (e.g., no ```sql).
    3. Do not add any explanations or text.
    4. Use JOINs correctly based on the provided schema.
    5. CRITICAL LANGUAGE & FORMAT RULE: The database only stores category names in Portuguese (product_category_name) and English (product_category_name_english). 
    Furthermore, the English names are ALWAYS formatted in lowercase with underscores instead of spaces (e.g., 'health_beauty', 'watches_gifts', 'bed_bath_table', 'sports_leisure'). 
    If the chat history mentions categories in French, you MUST translate them to English AND format them with lowercase and underscores before putting them in the WHERE clause.
    """
    
    # Self-correction logic: if the state contains an error from a previous run
    if error:
        system_prompt += f"\n\nWARNING: Your previous query failed with this error: {error}. Please correct your SQL."
        
    # Combine the system prompt with the entire conversation history (which now includes the latest question)
    messages = [SystemMessage(content=system_prompt)] + state.get("messages", [])
    
    # Call the LLM
    response = llm.invoke(messages)
    generated_sql = response.content.strip()
    
    print(f"Generated SQL:\n{generated_sql}\n")
    
    # Return the updated state
    return {"sql_query": generated_sql}

# 4. Define Node 2: Database Executor
def execute_sql(state: AgentState) -> dict:
    """
    Node 2: Executes the generated SQL query against the SQLite database.
    If it succeeds, it returns the data. If it fails, it returns the exact SQL error.
    """
    print("--- NODE: EXECUTING SQL ---")
    query = state.get("sql_query")
    
    if not query:
        return {"error": "No SQL query was generated."}
        
    try:
        # Connect to the local SQLite database
        conn = sqlite3.connect("olist.db")
        cursor = conn.cursor()
        
        # Execute the SQL query
        cursor.execute(query)
        
        # Fetch results (limiting to 100 to avoid blowing up the LLM context later)
        results = cursor.fetchmany(100)
        
        # Extract column names for better readability
        column_names = [description[0] for description in cursor.description]
        conn.close()

        # Create a structured list of dictionaries for Streamlit
        raw_data_list = [dict(zip(column_names, row)) for row in results]
        
        # Format the output
        if not results:
            formatted_results = "No results found."
        else:
            formatted_results = f"Columns: {', '.join(column_names)}\nData:\n"
            for row in results:
                formatted_results += str(row) + "\n"
                
        print("✓ Execution successful. Data fetched.\n")
        # Return the results and clear any previous errors
        return {"db_results": formatted_results, "raw_data": raw_data_list, "error": ""}
        
    except Exception as e:
        # If SQLite throws an error (e.g., column doesn't exist, syntax error)
        error_msg = f"SQLite Error: {str(e)}"
        print(f"✗ Execution failed! {error_msg}\n")
        return {"error": error_msg}

# 5. Define Node 3: Synthesizer / Summarizer
def summarize_results(state: AgentState) -> dict:
    """
    Node 3: Takes the raw database results and translates them into a 
    clear, business-friendly summary using the LLM.
    """
    print("--- NODE: SUMMARIZING RESULTS ---")
    question = state.get("query")
    raw_data = state.get("db_results")
    error = state.get("error")
    
    # If there's an error and we ended up here somehow, handle it
    if error:
        return {"summary": f"I couldn't answer the question due to an error: {error}"}
        
    llm = ChatOpenAI(model="gpt-4o-mini", temperature=0)
    
    system_prompt = """You are a helpful business data analyst. 
    You are provided with a user's original question and the raw data results from a SQL database.
    Your job is to write a clear, concise, and professional answer.
    CRITICAL RULE: You must explicitly list the key data points (e.g., category names, numbers, IDs) in your natural language response. Do not assume the user can read the raw table. If the data contains 5 categories, name all 5 of them in your text.
    Do not mention SQL, databases, or raw formatting."""
    
    messages = [
        SystemMessage(content=system_prompt),
        HumanMessage(content=f"Question: {question}\n\nRaw Data:\n{raw_data}")
    ]
    
    response = llm.invoke(messages)
    summary = response.content.strip()
    
    print("✓ Summary successfully generated.\n")
    return {
     "summary": summary, 
     "messages": [AIMessage(content=summary)] # Save the AI's answer to memory
    }

# 6. Define the Routing Logic (Conditional Edge)
def check_for_errors(state: AgentState) -> str:
    """
    Decides where the agent should go next after executing the SQL.
    If there is an error, route back to the SQL Generator to fix it.
    If successful, route to the Summarizer.
    """
    error = state.get("error")
    if error:
        print("--- ROUTING: ERROR DETECTED, RETRYING SQL GENERATION ---")
        return "generate_sql"
    else:
        print("--- ROUTING: SUCCESS, PROCEEDING TO SUMMARY ---")
        return "summarize_results"

# 7. Build and Compile the Graph
def create_graph():
    """
    Assembles the individual nodes and edges into a compiled LangGraph workflow.
    """
    # Initialize the memory saver to persist state between interactions
    memory = MemorySaver()
    
    # Initialize the graph with our custom State
    workflow = StateGraph(AgentState)
    
    # Add our three nodes
    workflow.add_node("generate_sql", generate_sql)
    workflow.add_node("execute_sql", execute_sql)
    workflow.add_node("summarize_results", summarize_results)
    
    # Define the execution flow
    workflow.add_edge(START, "generate_sql")
    workflow.add_edge("generate_sql", "execute_sql")
    
    # Add the conditional routing after DB execution
    workflow.add_conditional_edges(
        "execute_sql",
        check_for_errors,
        {
            "generate_sql": "generate_sql",           # Loop back on error
            "summarize_results": "summarize_results"  # Move forward on success
        }
    )
    
    workflow.add_edge("summarize_results", END)
    
    # Compile the graph into an executable application
    return workflow.compile(checkpointer=memory)

# 8. Quick Test Block
if __name__ == "__main__":
    # Initialize the compiled LangGraph agent
    agent_graph = create_graph()
    
    # We ask a trick question: the schema DOES NOT have a customer "name" column.
    # This should force the LLM to make a mistake, triggering the self-correction loop!
    test_state = {"query": "Can you give me the names of 3 customers from sao paulo?"}
    
    print("🚀 Starting the agentic workflow...\n")
    
    # Invoke the graph
    final_state = agent_graph.invoke(test_state)
    
    print("\n=== FINAL BUSINESS ANSWER ===")
    print(final_state.get("summary"))