import os
from dotenv import load_dotenv
from typing import TypedDict, List, Annotated
from operator import add
from langchain_core.messages import BaseMessage, SystemMessage, HumanMessage
from langchain_openai import ChatOpenAI

# 1. Load environment variables from the .env file (API keys)
load_dotenv()

# 2. Define the Agent's Memory
class AgentState(TypedDict, total=False):
    """
    Defines the shared state for the Text-to-SQL agent graph.
    """
    query: str                  # The user's natural language question
    sql_query: str              # The SQL query generated by the LLM
    db_results: str             # The raw data returned from the SQLite database
    error: str                  # Any SQL execution error
    summary: str                # The final, business-friendly answer
    messages: Annotated[List[BaseMessage], add] 

# 3. Define Node 1: SQL Generator
def generate_sql(state: AgentState) -> dict:
    """
    Node 1: Takes the user query and the database schema, 
    and uses an LLM to generate a valid SQLite query.
    If an error occurred in a previous step, it uses it to self-correct.
    """
    print("--- NODE: GENERATING SQL ---")
    question = state.get("query")
    error = state.get("error", "")
    
    # Read the database schema we extracted earlier
    try:
        with open("schema.txt", "r", encoding="utf-8") as f:
            schema = f.read()
    except FileNotFoundError:
        schema = "Schema file not found. Please run extract_schema.py first."
        
    # Initialize the LLM (using gpt-4o-mini for speed and cost efficiency)
    # Temperature is set to 0 because we want deterministic, precise SQL code, not creativity
    llm = ChatOpenAI(model="gpt-4o-mini", temperature=0)
    
    # Craft the system prompt
    system_prompt = f"""You are an expert SQLite data analyst.
    Your task is to translate the user's question into a valid SQLite query.
    
    Here is the schema of the database:
    {schema}
    
    Rules:
    1. Return ONLY the raw SQL query.
    2. Do not wrap the SQL in markdown formatting (e.g., no ```sql).
    3. Do not add any explanations or text.
    4. Use JOINs correctly based on the provided schema.
    """
    
    # Self-correction logic: if the state contains an error from a previous run
    if error:
        system_prompt += f"\n\nWARNING: Your previous query failed with this error: {error}. Please correct your SQL."
        
    messages = [
        SystemMessage(content=system_prompt),
        HumanMessage(content=question)
    ]
    
    # Call the LLM
    response = llm.invoke(messages)
    generated_sql = response.content.strip()
    
    print(f"Generated SQL:\n{generated_sql}\n")
    
    # Return the updated state
    return {"sql_query": generated_sql}

# 4. Quick Test Block
if __name__ == "__main__":
    # We simulate an initial state with a simple question
    test_state = {"query": "How many customers are there in the city of 'sao paulo'?"}
    
    # Run the node
    new_state = generate_sql(test_state)